// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjayGXVqvs9jYj-W4GxOJx0_MjyfI9M98',
    appId: '1:603444179956:web:2164c6f188ddb61e04bfa1',
    messagingSenderId: '603444179956',
    projectId: 'maxx-1fb5f',
    authDomain: 'maxx-1fb5f.firebaseapp.com',
    storageBucket: 'maxx-1fb5f.appspot.com',
    measurementId: 'G-7ZM8EV9PB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5kJPsXNO6DVT-oN8tdf9L7eF_qa2HwI',
    appId: '1:603444179956:android:3c67fb29a8b7de5104bfa1',
    messagingSenderId: '603444179956',
    projectId: 'maxx-1fb5f',
    storageBucket: 'maxx-1fb5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdMKbc4a9nBzsIJBKDySjQzH4MeVUhGes',
    appId: '1:603444179956:ios:0bd4561928c43bc304bfa1',
    messagingSenderId: '603444179956',
    projectId: 'maxx-1fb5f',
    storageBucket: 'maxx-1fb5f.appspot.com',
    iosBundleId: 'com.example.max',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdMKbc4a9nBzsIJBKDySjQzH4MeVUhGes',
    appId: '1:603444179956:ios:0bd4561928c43bc304bfa1',
    messagingSenderId: '603444179956',
    projectId: 'maxx-1fb5f',
    storageBucket: 'maxx-1fb5f.appspot.com',
    iosBundleId: 'com.example.max',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjayGXVqvs9jYj-W4GxOJx0_MjyfI9M98',
    appId: '1:603444179956:web:1750399e0b9820b404bfa1',
    messagingSenderId: '603444179956',
    projectId: 'maxx-1fb5f',
    authDomain: 'maxx-1fb5f.firebaseapp.com',
    storageBucket: 'maxx-1fb5f.appspot.com',
    measurementId: 'G-RY23RMYP1M',
  );
}
